### ISSUE TITLE
How do we use it?

### ISSUE THREAD

**Issue by dooferorg** [digital195/unifi-protect-viewer#1]
Like the one this is based on, it's a nice idea, but the instructions leave something to be desired. Once installed, what URL do we go to in order to 'load it'. There is nothing showing as an extension button or icon in the browser extension area. I'm trying this in Chromium on a Raspberry Pi and it doesn't do anything.

Edit: I will also mention that there are no errors on starting chromium-browser from the console that indicates it's trying to load and failing. Going to the 'protect.html' directly via a file:// link appears to load it but it still does nothing (blank white page). No javascript errors are in the console either.

**Comment by digital195** [comment]
Hey,

first it's a chroma app, so there is no url you need to open. It's an application on host level which runs as a chroma application.

you need to configure the application for your needs.

You need to change 3 values in 2 files as listet in the readme.md
First you need to change the url to the of your protect instance, in my case my udm pro is running under https://192.168.1.1, so i have to enter `https://192.168.1.1/login?redirect=%2Fprotect%2Fliveview` as the url in the protect.html file. After that i need to add my login credentials into the project.js file (change %USERNAME% and %PASSWORD% to your login credentials). After that the application is configured. 

Next you need to open chrome on your pi and open this page `chrome://extensions/`, then enable the developer mode on the top right of the screen. Now you can click `load unpacked` and select the app folder of the application. Then you will see something like this under chrome apps.

Now you can run the chrome app like a normal programm, under windows you can find it in your start menu. On the raspberry pi you can find it under chrome apps.

For kioks mode i thing you need to zip the folder and rename the end to .crx, but i'm not sure.

You won't be able to start the html file directly with your browser. It needs to be opened as a chrome application. I have not testet this with kioks mode so can't tell you what you need to do, but i know that this is working on my raspberry pi 4.

When you need any other help just let me know with a more detailed note of what you did so far.

**Comment by dooferorg** [comment]
*Ah!* .. after rebooting the pi I saw the Chromium apps thing. I really thought I'd see *something* happening in the browser itself. Thank you, that was what I was missing in it all. I'd never used chrome apps before.

It seemed to do ok, but was in a small window and didn't do the 'full screen' thing like clicking the button in protect. The correct live view URL was pulled up though, so that was good.

**Comment by digital195** [comment]
You could try to uncomment this in the main.js file

![grafik](https://user-images.githubusercontent.com/56077368/130540886-2e24bff0-3adb-47a2-860a-ea16573ccf8e.png)

and change the state to fullscreen like in the comment next to it

Then the app will start as a full screen application.
