### ISSUE TITLE
No support for Windows, macOs, Linux after December 2022

### ISSUE THREAD

**Issue by ghoeffner** [digital195/unifi-protect-viewer#2]
Hey there, getting a warning when starting about this: https://support.google.com/chrome_webstore/answer/3060053?
Unfortunately, that means we will once again find a new solution :-( 

Thanks for your work on this extension so far - right now it is working flawlessly.

**Comment by digital195** [comment]
I plan to rewrite the Chrome app into an Electron app. This should also run on all systems depending on the build. My test app works very well on windows and mac os.

![grafik](https://user-images.githubusercontent.com/56077368/198654060-f704386f-df9a-4c26-b815-4643d0996f6c.png)

I am currently testing if the version runs without problems and will put the source code and executables in this repository when its done. Unfortunately I don't know how it will work with Raspberry Pi or other small devices.

**Comment by digital195** [comment]
the version is now in the repository [digital195/unifi-protect-viewer](https://github.com/digital195/unifi-protect-viewer)
