### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by thisIsLiving** [digital195/unifi-protect-viewer#3]
Thanks for the great work! Is there a way to get the app to remember the window size after resizing it? Similar to how it remembers in the Chrome app?

Also it pops up with an unsupported browser notification that I think you automatically dismiss. No way around it? I read somewhere it should store a cookie after the first time the notification is dismissed.

**Comment by digital195** [comment]
i have added some code to make it remember its position and size. Also the unsupported browser warning should be gone.
