### ISSUE TITLE
Binary downloads

### ISSUE THREAD

**Issue by ghoeffner** [digital195/unifi-protect-viewer#4]
The "readme" currently states: "Ether you can download this application from github or build it yourself with this repository."
I couldn't find the binary for Windows anywhere. did I miss something?

**Comment by digital195** [comment]
Sry, i forgot to add them. You can download them from here , they are just electron build so you can simply unzip the folder and use the application. There is no install required. If you need the build for other platforms, please just build the app yourself with electron :)

https://github.com/digital195/unifi-protect-viewer/releases/tag/v0.1.0
