### ISSUE TITLE
Feature Request: Multiple sites

### ISSUE THREAD

**Issue by n9yty** [digital195/unifi-protect-viewer#6]
Feature Request: Allow multiple protect servers

It would be nice to be able to have multiple servers configured and switch between them, or possibly have them in a split view or tab to view them simultaneously?

Also, once configured, I'm not seeing a way to change the URL to even switch to another server.

**Comment by n9yty** [comment]
I found the configuration under:

~/Library/Application Support/unifi-protect-viewer

**Comment by digital195** [comment]
currently you can reset the configuration using the hotkeys. Then the configuration will be started again.

    F9 Restart
    F10 Restart & Reset
    F11 Fullscreen (Electron, no Unifi Protect Fullscreen)
