### ISSUE TITLE
Video not "full-screen" when starting with windows startup

### ISSUE THREAD

**Issue by ghoeffner** [digital195/unifi-protect-viewer#7]
Hello, I am currently using unifi-protect-viewer in an automated setup. When the computer starts it automatically starts the application using a shortcut in "shell:startup". Everything works as expected, except the video does not become "full-screen" and sometimes even the sidebar does not get closed. 

Maybe this is something that could be fixed (maybe even with a time delay?)

**Comment by digital195** [comment]
i had planned to move the fixed wait to a conditional wait until the ui from protect is fully loaded (something like the css classes/ panels are present and then remove them). This could potentially fix your problem. I will take a look at this in the next few days.

what kind of device is protect running (udm, router, nvr ...) on and are you using protect v2 or v3?

**Comment by ghoeffner** [comment]
Currently running protect v3 on a UDM Pro (UniFi OS v3.2.12)

**Comment by digital195** [comment]
I have revised the waiting logic so that it depends on the presence of the dom elements.
I also added a reload after the token expires. 

Please let me know if version 0.2.1 fixes the problems.

https://github.com/digital195/unifi-protect-viewer/releases/tag/v0.2.1

**Comment by ghoeffner** [comment]
Just tested the linked version and I still see the same behavior where it does not "full screen" (or zoom?) the screen. But this time it also doesn't do it when starting it manually :-D

**Comment by digital195** [comment]
funny, I added some debug output to the linked version. Feel free to test the version and add the output to the issue (you can remove the ip and url). You can get the output by pressing CTRL + SHIFT + I in the application and looking at the console in the development tools.

https://github.com/digital195/unifi-protect-viewer/releases/download/v0.2.1/unifi-protect-viewer-portable-win32-ia32-1-debug.zip

the output should look like this:
![grafik](https://github.com/digital195/unifi-protect-viewer/assets/56077368/2e7eaea6-8840-4ffc-a47c-2b0dc9bb2b45)

then we can check where the script fails and what the cause might be

**Comment by minchaminder** [comment]
hack to get Unifi protect full screen mode https://github.com/minchaminder/unifi-protect-electron-viewer/blob/cf5806a1c9b8365399935b3f28359e86a20ecc08/index.js#L208
